apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: parser
  name: parser
  namespace: infohub
spec:
  replicas: 1
  selector:
    matchLabels:
      run: parser
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: parser
    spec:
      containers:
      - image: 827461279864.dkr.ecr.sa-east-1.amazonaws.com/CURRENT_IMAGE
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: ASPNETCORE_ENVIRONMENT
              name: parser
        imagePullPolicy: Always
        name: parser
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30